version: '3'
services: 

  jenkins-blueocean:
    image: jenkinsci/blueocean
    container_name: "jenkins-blueocean"
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
